module ntt46_p520_ntt46_fact_top_prod_load16 #(
  parameter int unsigned R = 512,
  parameter int unsigned LANES = 16,
  parameter bit PRODUCT_STORE_DEPTH8 = 1'b1,
  parameter bit USE_PRODUCT32_STREAM = 1'b1,
  parameter bit PRODUCT32_USE_PACKED_FIFO = 1'b1,
  parameter bit PRODUCT32_RESET_DATA_ARRAYS = 1'b1,
  parameter bit PRODUCT32_INPUT_PIPELINE = 1'b0,
  parameter bit PRODUCT32_ZERO_INVALID_OUTPUTS = 1'b1,
  parameter bit USE_PRODUCT64_STREAM = 1'b0,
  parameter bit PRODUCT64_DRAIN_DURING_INVERSE = 1'b0,
  parameter bit PRODUCT_STORE_SPLIT_SLOTS = 1'b0,
  parameter bit PRODUCT_STORE_DUAL_READ = 1'b0,
  parameter bit PRODUCT_READY_CLEAR_ON_ACCUM = 1'b0,
  parameter bit STORE_USE_XPM = 1'b0,
  parameter bit TRANSFORM_J_USE_DSP = 1'b1,
  parameter bit TRANSFORM_J_LUT_FAST3 = 1'b0,
  parameter bit TRANSFORM_J_MUL_TIGHT = 1'b1,
  parameter bit TRANSFORM_TWIDDLE_PRE_STAGE = 1'b0,
  parameter bit TRANSFORM_TWIDDLE_PREFETCH_STAGE = 1'b1,
  parameter bit SLOT_WRITE_PIPELINE = 1'b1,
  parameter bit INVERSE_OUTPUT_PIPELINE = 1'b1,
  parameter bit TERMINAL_INPUT_PIPELINE = 1'b1,
  parameter bit TERMINAL_RESET_DATA_ARRAYS = 1'b1,
  parameter bit RESET_WR_PIPE_DATA = 1'b1,
  parameter bit FORWARD_OUTPUT_PIPELINE = 1'b0,
  parameter int unsigned SLOT_DEPTH_CFG = 3,
  parameter int unsigned META_DEPTH_CFG = 16,
  parameter bit FACT_AREA_TRIM_CTRL = 1'b0,
  parameter bit FACT_AREA_TRIM_CORE_DATA = FACT_AREA_TRIM_CTRL,
  parameter bit FACT_AREA_TRIM_STEP_DATA = FACT_AREA_TRIM_CTRL,
  parameter bit FACT_LOCAL_PREDECODE = 1'b0,
  parameter bit FACT_EXT_STAGE0_ENABLE = 1'b0,
  parameter int unsigned R512_L8_SCHED_MODE = 0,
  parameter bit ENABLE_DEBUG_OUTPUTS = 1'b0
) (
  input  logic                                clk,
  input  logic                                rst,
  input  logic                                load_en,
  input  logic [8:0]                          load_idx,
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     plus_load_data,
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     minus_load_data,
  input  logic                                load16_en,
  input  logic [4:0]                          load16_idx,
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     plus_load16_data [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     minus_load16_data [0:LANES-1],
  output logic                                ext_stage0_rd_en,
  output logic [$clog2(R/(2*LANES))-1:0]      ext_stage0_rd_batch,
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_plus_y0 [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_plus_y1 [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_plus_y2 [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_plus_y3 [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_minus_y0 [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_minus_y1 [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_minus_y2 [0:LANES-1],
  input  ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     ext_stage0_minus_y3 [0:LANES-1],
  input  logic                                start,
  input  logic                                run_forward,
  input  logic                                forward_product_odd,
  input  logic                                forward_clear_accum,
  output logic                                busy,
  output logic                                done,
  output logic [15:0]                         compute_cycles,
  output logic                                out_valid,
  output logic [$clog2(R/(2*LANES))-1:0]      out_batch,
  output ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     low_y0 [0:LANES-1],
  output ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     high_y0 [0:LANES-1],
  output ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     low_y1 [0:LANES-1],
  output ntt46_p520_ntt46_mrec_arith_pkg::mrec_res_t     high_y1 [0:LANES-1]
);

  ntt46_p520_ntt46_fact_runtime_shared_pair_product16_streamed_bram_r512 #(
    .R(R),
    .LANES(LANES),
    .PRODUCT_STORE_DEPTH8(PRODUCT_STORE_DEPTH8),
    .USE_PRODUCT32_STREAM(USE_PRODUCT32_STREAM),
    .PRODUCT32_USE_PACKED_FIFO(PRODUCT32_USE_PACKED_FIFO),
    .PRODUCT32_RESET_DATA_ARRAYS(PRODUCT32_RESET_DATA_ARRAYS),
    .PRODUCT32_INPUT_PIPELINE(PRODUCT32_INPUT_PIPELINE),
    .PRODUCT32_ZERO_INVALID_OUTPUTS(PRODUCT32_ZERO_INVALID_OUTPUTS),
    .USE_PRODUCT64_STREAM(USE_PRODUCT64_STREAM),
    .PRODUCT64_DRAIN_DURING_INVERSE(PRODUCT64_DRAIN_DURING_INVERSE),
    .TRANSFORM_J_USE_DSP(TRANSFORM_J_USE_DSP),
    .TRANSFORM_J_LUT_FAST3(TRANSFORM_J_LUT_FAST3),
    .TRANSFORM_J_MUL_TIGHT(TRANSFORM_J_MUL_TIGHT),
    .TRANSFORM_TWIDDLE_PRE_STAGE(TRANSFORM_TWIDDLE_PRE_STAGE),
    .TRANSFORM_TWIDDLE_PREFETCH_STAGE(TRANSFORM_TWIDDLE_PREFETCH_STAGE),
    .SLOT_WRITE_PIPELINE(SLOT_WRITE_PIPELINE),
    .INVERSE_OUTPUT_PIPELINE(INVERSE_OUTPUT_PIPELINE),
    .TERMINAL_INPUT_PIPELINE(TERMINAL_INPUT_PIPELINE),
    .TERMINAL_RESET_DATA_ARRAYS(TERMINAL_RESET_DATA_ARRAYS),
    .RESET_WR_PIPE_DATA(RESET_WR_PIPE_DATA),
    .FORWARD_OUTPUT_PIPELINE(FORWARD_OUTPUT_PIPELINE),
    .SLOT_DEPTH_CFG(SLOT_DEPTH_CFG),
    .META_DEPTH_CFG(META_DEPTH_CFG),
    .PRODUCT_STORE_SPLIT_SLOTS(PRODUCT_STORE_SPLIT_SLOTS),
    .PRODUCT_STORE_DUAL_READ(PRODUCT_STORE_DUAL_READ),
    .PRODUCT_READY_CLEAR_ON_ACCUM(PRODUCT_READY_CLEAR_ON_ACCUM),
    .STORE_USE_XPM(STORE_USE_XPM),
    .ENABLE_LOAD16(1'b1),
    .FACT_AREA_TRIM_CTRL(FACT_AREA_TRIM_CTRL),
    .FACT_AREA_TRIM_CORE_DATA(FACT_AREA_TRIM_CORE_DATA),
    .FACT_AREA_TRIM_STEP_DATA(FACT_AREA_TRIM_STEP_DATA),
    .FACT_LOCAL_PREDECODE(FACT_LOCAL_PREDECODE),
    .FACT_EXT_STAGE0_ENABLE(FACT_EXT_STAGE0_ENABLE),
    .R512_L8_SCHED_MODE(R512_L8_SCHED_MODE),
    .ENABLE_DEBUG_OUTPUTS(ENABLE_DEBUG_OUTPUTS)
  ) u_core (
    .clk, .rst, .load_en, .load_idx, .plus_load_data, .minus_load_data,
    .load16_en, .load16_idx, .plus_load16_data, .minus_load16_data,
    .ext_stage0_rd_en, .ext_stage0_rd_batch,
    .ext_stage0_plus_y0, .ext_stage0_plus_y1, .ext_stage0_plus_y2, .ext_stage0_plus_y3,
    .ext_stage0_minus_y0, .ext_stage0_minus_y1, .ext_stage0_minus_y2, .ext_stage0_minus_y3,
    .start, .run_forward, .forward_product_odd, .forward_clear_accum,
    .busy, .done, .compute_cycles, .out_valid, .out_batch,
    .low_y0, .high_y0, .low_y1, .high_y1,
    .stream_batch_mismatch(), .stream_radix2_seen(),
    .product_stream_queued(), .product_write_valid(),
    .product_write_odd(), .product_write_batch()
  );

endmodule

